###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      restart: always
      container_name: cars-mariadb
      working_dir: /application
      # volumes:
      #   - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_USER=${DATABASE_USER}
        - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      ports:
        - "${DATABASE_PORT}:3306"

    webserver:
      image: nginx:alpine
      container_name: cars-webserver
      working_dir: /application
      volumes:
          - ../src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${APP_PORT}:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: cars-php-fpm
      working_dir: /application
      depends_on: 
        - mariadb
      # command: bin/bin
      environment:
        - APP_ENV=${APP_ENV}
        - APP_SECRET=${APP_SECRET}
        - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mariadb:${DATABASE_PORT}/${DATABASE_NAME}?serverVersion=${DATABASE_SERVER_VERSION}&charset=utf8
      volumes:
        - ../src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    # mercure:
    #   # In production, you may want to use the managed version of Mercure, https://mercure.rocks
    #   image: dunglas/mercure
    #   environment:
    #     # You should definitely change all these values in production
    #     - JWT_KEY=${MERCURE_JWT_TOKEN} # You have to change MERCURE_JWT_TOKEN in src/.env when you change this. You can put the old value of MERCURE_JWT_TOKEN into the debugger on https://jwt.io/ and put the new value of JWT_KEY in the "secret" field to obtain the new encoded value for MERCURE_JWT_TOKEN
    #     - ALLOW_ANONYMOUS=1
    #     - CORS_ALLOWED_ORIGINS=*
    #     - PUBLISH_ALLOWED_ORIGINS=http://localhost:1337 https://localhost:1338
    #     - DEMO=1
    #   ports:
    #     - "1337:80"

