###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    mariadb:
      image: mariadb:10.4
      restart: always
      container_name: cars-mariadb
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_USER=${DATABASE_USER}
        - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      ports:
        - "${DATABASE_PORT}:3306"

    webserver:
      image: nginx:alpine
      container_name: cars-webserver
      working_dir: /application
      volumes:
          - ../logs/nginx:/var/log/nginx:cached
          - ../src_back:/application/back
          - ../src_front:/application/frontend
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${APP_PORT}:80"
       - "8080:8080"

    node:
      build: phpdocker/node
      container_name: cars-node
      working_dir: /application/frontend
      ports:
       - "4200:4200"
      volumes:
        - ../src_front:/application/frontend

    php-fpm:
      build: phpdocker/php-fpm
      container_name: cars-php-fpm
      working_dir: /application/back
      depends_on: 
        - mariadb
      # command: bin/bin
      environment:
        - APP_ENV=${APP_ENV}
        - APP_SECRET=${APP_SECRET}
        - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mariadb:${DATABASE_PORT}/${DATABASE_NAME}?serverVersion=${DATABASE_SERVER_VERSION}&charset=utf8
      volumes:
        - ../src_back:/application/back
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
